Add portfolio desktop
bimbolabuari/mv-portfolio pull request #4
Opened 2021-06-09 16:47 UTC by bimbolabuari

# Portfolio Microverse Project  🚀 

 > This PR adds a project about building a portfolio with  HTML and CSS that demonstrates the knowledge of Semantic HTML, flexbox, background properties, and mobile-first responsiveness, Responsive web design, CSS media query.

## Built With 🙂 

- Semantic HTML & CSS
- Linters (Stylelint, Web hint, Lighthouse)

## Live Preview  🎉 

[Live Preview Link](https://deploy-preview-4--bimbola-mv-portfolio.netlify.app/)

## Note to code reviewer 👍 
> 1. I used [Figma template 2](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)  using its color, font, and images.  
> 2. The live demo link on the readme is for the main branch, hence it is not yet deployed until merged. Please use this [deployed preview](https://deploy-preview-4--bimbola-mv-portfolio.netlify.app/) (also attached above).

2021-06-09 18:24 UTC, Shaher-11 requested changes
Hello @bimbolabuari  

#### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:blush::blush:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [x] Kindly align the text in the about me section with the image as shown below.
- [x] The text beside the from should be equal to the form height.

## Original Design
![right](https://user-images.githubusercontent.com/58376020/121408285-888e4280-c960-11eb-84ad-948440b4b87c.png)

## Your project
![wrong1](https://user-images.githubusercontent.com/58376020/121408332-993eb880-c960-11eb-9d16-c08d36d1a6de.png)

![wrong2](https://user-images.githubusercontent.com/58376020/121408395-a8256b00-c960-11eb-85ac-be335d599514.png)



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-06-09 19:31 UTC, Shaher-11 reviewed
## _Status:_ Invalid:x:
## Hello @bimbolabuari 
This Code Review Request will be marked as invalid in your Dashboard because the linter checks are not passed.
Please make the necessary changes and submit another code review request once you are ready! :smiley:

2021-06-09 20:32 UTC, henatan99 approved these changes
Hi Abimbola, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- Please take note of the OPTIONAL comments because they are really important even though they are OPTIONAL and not needed for this project's submission. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 20:32 UTC, henatan99 commented on styles.css
> +@media only screen and (min-width: 970px) {
- [ ] OPTIONAL: This min-width value should serve minimum width for desktop version and better to make it in the range 992px-1100px. Yours is a bit smaller than standard desktop widths.

2021-06-09 20:32 UTC, henatan99 commented on styles.css
> +  }
- [ ] OPTIONAL: The greetings element seems to take not more than in the original design, so I suggest you give a width of about 50% for desktop view. Kindly, compare yours and the original design from the attached screenshot images.
![image](https://user-images.githubusercontent.com/64894927/121423017-7e783e00-c978-11eb-92ce-23ac30b8d374.png)   
![image](https://user-images.githubusercontent.com/64894927/121423098-9485fe80-c978-11eb-87cd-9db0fcb267d4.png)

2021-06-09 20:32 UTC, henatan99 commented on index.html
>        <h2 class="work-header">My recent Works</h2>
- [ ] OPTIONAL: This header is aligned left and also followed by a horizontal line to the end in the original design. Kindly compare yours and the original design from the screenshot images below. 
![image](https://user-images.githubusercontent.com/64894927/121423685-34dc2300-c979-11eb-916c-ccf4d4bf989d.png)    
![image](https://user-images.githubusercontent.com/64894927/121423722-402f4e80-c979-11eb-8ca6-d4c131ee96ff.png)

2021-06-09 20:32 UTC, henatan99 commented on index.html
> +        <div class="work-container">
- [ ]  OPTIONAL: The width proportions of the `img-works` and `work-container` classes inside the works element is not as the original design. Please see the attached images for comparison. 
- [ ] OPTIONAL: Color differences of some element is also there. 
- [ ] OPTIONAL: Same is true for the `btn-flex` class child elements. 
![image](https://user-images.githubusercontent.com/64894927/121424266-d2cfed80-c979-11eb-80bc-afe566871593.png)   
![image](https://user-images.githubusercontent.com/64894927/121424313-e11e0980-c979-11eb-9b24-ef64b4edff58.png)

2021-06-11 15:43 UTC, bimbolabuari commented
@henatan99, Thanks for approving my project 🎉, I have made all the optional changes 🙂

2021-06-12 00:08 UTC, merged